import { PlatformRules } from './compliance.interface';

export const DEFAULT_PLATFORM_RULES: Record<string, PlatformRules> = {
  x: {
    platform: 'x',
    maxCharacters: 280,
    maxImages: 4,
    maxVideoLengthSec: 140,
    maxPostsPerHour: 50,
    maxPostsPerDay: 500,
    maxRepliesPerHour: 100,
    minSecBetweenPosts: 30,
    requireBotLabel: false,
    botLabelFormat: '#AutomatedPost',
    requireAltText: false,
    hashtagLimit: null,
    forbiddenPatterns: [],
    apiCostPerPost: 0,
    notes: 'Bot label only required when posts are fully autonomous (no human review). When human-in-the-loop approves each post, content is human-curated and no bot label is needed.',
  },

  linkedin: {
    platform: 'linkedin',
    maxCharacters: 3000,
    maxImages: 20,
    maxVideoLengthSec: 600,
    maxPostsPerHour: 10,
    maxPostsPerDay: 50,
    maxRepliesPerHour: 30,
    minSecBetweenPosts: 120,
    requireBotLabel: false,
    botLabelFormat: '[Automated]',
    requireAltText: false,
    hashtagLimit: 30,
    forbiddenPatterns: [],
    apiCostPerPost: 0,
    notes: 'Bot label not strictly required but recommended for transparency. LinkedIn may throttle automated content.',
  },

  bluesky: {
    platform: 'bluesky',
    maxCharacters: 300,
    maxImages: 4,
    maxVideoLengthSec: 60,
    maxPostsPerHour: 30,
    maxPostsPerDay: 300,
    maxRepliesPerHour: 60,
    minSecBetweenPosts: 30,
    requireBotLabel: false,
    botLabelFormat: null,
    requireAltText: false,
    hashtagLimit: null,
    forbiddenPatterns: [],
    apiCostPerPost: 0,
    notes: 'Bot-friendly platform with labeler system. Bots can self-label via the AT Protocol labeler.',
  },

  threads: {
    platform: 'threads',
    maxCharacters: 500,
    maxImages: 10,
    maxVideoLengthSec: 300,
    maxPostsPerHour: 25,
    maxPostsPerDay: 250,
    maxRepliesPerHour: 50,
    minSecBetweenPosts: 60,
    requireBotLabel: false,
    botLabelFormat: null,
    requireAltText: false,
    hashtagLimit: null,
    forbiddenPatterns: [],
    apiCostPerPost: 0,
    notes: 'Uses Meta content publishing API. Rate limits enforced by Meta.',
  },

  mastodon: {
    platform: 'mastodon',
    maxCharacters: 500,
    maxImages: 4,
    maxVideoLengthSec: 120,
    maxPostsPerHour: 30,
    maxPostsPerDay: 300,
    maxRepliesPerHour: 60,
    minSecBetweenPosts: 30,
    requireBotLabel: false,
    botLabelFormat: null,
    requireAltText: true,
    hashtagLimit: null,
    forbiddenPatterns: [],
    apiCostPerPost: 0,
    notes: 'Bot label (profile flag) only needed for fully autonomous accounts. Human-reviewed posts are human-curated. Alt text strongly encouraged by community norms.',
  },
};
